title: Nadia Wadzinski 
theme: jekyll-theme-minimal
logo: /images/avatar6.png?raw=true
description: Seattle Sr Staff Software Engineer
blurb: > 
  <p>
    Senior Staff software engineer based in Seattle, working on distributed systems, 
    databases, performance, SRE, and AI tools.
    Currently at <a href="https://www.rover.com/">Rover.com</a>.
  </p>
email: nadia.wadzinski@gmail.com
show_downloads: false
# google_analytics: false
linkedin: https://www.linkedin.com/in/nadia-wadzinski-a069ab11a/
